const ListaDeOrçamentos = [
  {
    id: 1,
    cliente: "TRHK Engenharia",
    nifDoCliente: 553662162,
    categoria: "Reforma",
    dataDaEmissao: "12/05/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 2200,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },
  {
    id: 2,
    cliente: "Compesa S.A.",
    nifDoCliente: 553662162,
    categoria: "Construção",
    dataDaEmissao: "15/06/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 5200,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },
  {
    id: 3,
    cliente: "Rodrigues Oliveira",
    nifDoCliente: 553662162,
    categoria: "Obra",
    dataDaEmissao: "22/06/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 500,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },
  {
    id: 4,
    cliente: "ANJE",
    nifDoCliente: 553662162,
    categoria: "Pintura",
    dataDaEmissao: "28/06/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 2800,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },
  {
    id: 5,
    cliente: "Nova Construtora",
    nifDoCliente: 553662162,
    categoria: "Construção",
    dataDaEmissao: "05/07/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 4500,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },

  {
    id: 6,
    cliente: "Renovar Engenharia",
    nifDoCliente: 553662162,
    categoria: "Reforma",
    dataDaEmissao: "12/07/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 6200,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },

  {
    id: 7,
    cliente: "GreenGardens",
    nifDoCliente: 553662162,
    categoria: "Construção",
    dataDaEmissao: "18/07/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 5800,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },

  {
    id: 8,
    cliente: "Design Interiores",
    nifDoCliente: 553662162,
    categoria: "Pintura",
    dataDaEmissao: "21/07/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 4100,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },

  {
    id: 9,
    cliente: "Concreto Forte",
    nifDoCliente: 553662162,
    categoria: "Construção",
    dataDaEmissao: "02/08/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 2300,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },

  {
    id: 10,
    cliente: "Marcelo Pinturas",
    nifDoCliente: 553662162,
    categoria: "Pintura",
    dataDaEmissao: "10/08/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 3300,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },

  {
    id: 11,
    cliente: "Reciclar Sustentável",
    nifDoCliente: 553662162,
    categoria: "Reforma",
    dataDaEmissao: "16/08/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 1800,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },

  {
    id: 12,
    cliente: "Modernizar Residências",
    nifDoCliente: 553662162,
    categoria: "Construção",
    dataDaEmissao: "23/08/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 3800,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },

  {
    id: 13,
    cliente: "Alfa Engenharia",
    nifDoCliente: 553662162,
    categoria: "Obra Completa",
    dataDaEmissao: "01/09/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 2500,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },

  {
    id: 14,
    cliente: "PlanToPlant",
    nifDoCliente: 553662162,
    categoria: "Construção",
    dataDaEmissao: "07/09/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 4500,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },

  {
    id: 15,
    cliente: "Aquarela Piscinas",
    nifDoCliente: 553662162,
    categoria: "Pintura",
    dataDaEmissao: "14/09/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 58000,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },

  {
    id: 16,
    cliente: "EcoEnergia",
    nifDoCliente: 553662162,
    categoria: "Obra Completa",
    dataDaEmissao: "21/09/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 4100,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },

  {
    id: 17,
    cliente: "Pedras do Vale",
    nifDoCliente: 553662162,
    categoria: "Construção",
    dataDaEmissao: "28/09/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 8500,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },

  {
    id: 18,
    cliente: "Arte & Design",
    nifDoCliente: 553662162,
    categoria: "Pintura",
    dataDaEmissao: "05/10/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 5700,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },

  {
    id: 19,
    cliente: "Viver Bem",
    nifDoCliente: 553662162,
    categoria: "Reforma",
    dataDaEmissao: "12/10/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 6900,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },

  {
    id: 20,
    cliente: "Amigos do Rio",
    nifDoCliente: 553662162,
    categoria: "Obra Completa",
    dataDaEmissao: "19/10/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 9200,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },

  {
    id: 21,
    cliente: "EcoHabitat",
    nifDoCliente: 553662162,
    categoria: "Construção",
    dataDaEmissao: "26/10/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 2200,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },

  {
    id: 22,
    cliente: "Beleza Natural",
    nifDoCliente: 553662162,
    categoria: "Pintura",
    dataDaEmissao: "02/11/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 8500,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },

  {
    id: 23,
    cliente: "Urbanizar",
    nifDoCliente: 553662162,
    categoria: "Reforma",
    dataDaEmissao: "09/11/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 2300,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },

  {
    id: 24,
    cliente: "Limpar & Reciclar",
    nifDoCliente: 553662162,
    categoria: "Construção",
    dataDaEmissao: "16/11/2023",
    descriçao: "O projeto de reforma desta casa tem como objetivo revitalizar completamente o espaço, proporcionando uma residência moderna e funcional. Com foco na otimização do espaço, serão realizadas alterações estruturais para criar ambientes mais integrados e bem iluminados, utilizando materiais sustentáveis e de alta qualidade. A renovação inclui a modernização das instalações elétricas e hidráulicas, além da incorporação de tecnologias inteligentes para tornar a casa mais eficiente e automatizada. Serão aplicados conceitos de design contemporâneo para a seleção de móveis e acabamentos, buscando uma estética harmoniosa e acolhedora. O projeto também contempla o paisagismo, criando espaços externos atraentes e relaxantes. Em suma, essa reforma visa transformar a casa em um lar sofisticado, confortável e sustentável, atendendo plenamente às necessidades e expectativas dos seus moradores.",
    valorTotal: 1100,
    maoDeObra: [
      {
        id: 5213,
        nome: "Encanador",
        unid: "hr",
        valor: 250,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
      },
      {
        id: 12316,
        nome: "Pintor",
        unid: "m²",
        valor: 15,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
      },
      {
        id: 72342,
        nome: "Pedreiro de Acabamento",
        unid: "diárias",
        valor: 280,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
      },
      {
        id: 1318,
        nome: "Carpinteiro",
        unid: "hr",
        valor: 320,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
      }
    ],
    materiais: [
      {
        id: 1,
        nome: "Areia",
        unid: "m³",
        valor: 800,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "A areia é um material granular amplamente utilizado na construção civil para fazer argamassa, concreto e outros elementos estruturais. Ela é essencial na maioria das obras, sendo usada como material de base e preenchimento.",
      },
      {
        id: 2,
        nome: "Cimento",
        unid: "sacos",
        valor: 300,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "O cimento é um dos principais componentes do concreto e é utilizado para unir materiais de construção. Ele endurece e adquire resistência após a mistura com água, tornando-se uma das bases fundamentais da construção civil.",
      },
      {
        id: 3,
        nome: "Varões de Ferro",
        unid: "varões",
        valor: 1200,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "Varões de Ferro, também conhecido como barra de aço, é utilizado para reforçar estruturas de concreto, como vigas e pilares. Sua alta resistência à tração contribui para aumentar a capacidade de suporte das estruturas.",
      },
      {
        id: 4,
        nome: "Sapatas",
        unid: "Toneladas",
        valor: 3500,
        quantidade: 3,
        margem: 15,
        valortotal: 5800,
        descriçao: "As sapatas são elementos estruturais usados como base de fundação em construções. Elas distribuem o peso e as cargas da construção no solo, garantindo a estabilidade e segurança da edificação.",
      }
    ]
  },
]

export default ListaDeOrçamentos;