const ListaDeMaoDeObra = [
  {
    id: 112312,
    nome: "Pedreiro",
    unid: "diária",
    valor: 70,
    descriçao: "O pedreiro é um profissional da construção civil especializado em realizar diversas atividades relacionadas à alvenaria, como construção de paredes, reboco, assentamento de pisos e aplicação de revestimentos. Ele desempenha um papel fundamental em projetos de construção e reforma, garantindo a qualidade e segurança das estruturas",
  },
  {
    id: 212321,
    nome: "Eletricista",
    unid: "diária",
    valor: 70,
    descriçao: "O eletricista é responsável por realizar instalações e manutenções elétricas em residências, edifícios, empresas e indústrias. Ele lida com fiação, sistemas de iluminação, tomadas e equipamentos elétricos, garantindo o funcionamento seguro e adequado dos sistemas elétricos nos projetos de construção",
  },
  {
    id: 312312,
    nome: "Arquiteto",
    unid: "mes",
    valor: 1300,
    descriçao: "O arquiteto é um profissional criativo e técnico, responsável por projetar espaços e edifícios funcionais, esteticamente agradáveis e adequados às necessidades dos clientes. Ele trabalha desde o planejamento até a execução das obras, coordenando equipes e garantindo a viabilização dos projetos.",
  },
  {
    id: 4234,
    nome: "Engenheiro",
    unid: "mês",
    valor: 1500,
    descriçao: "O engenheiro é um profissional com formação técnica e científica, capacitado para projetar, construir e gerenciar obras e sistemas de infraestrutura. Ele é responsável por garantir a segurança, qualidade e eficiência dos projetos, supervisionando equipes e tomando decisões estratégicas durante a execução das obras.",
  },
  {
    id: 5213,
    nome: "Encanador",
    unid: "hr",
    valor: 250,
    descriçao: "Profissional responsável por instalar e reparar sistemas de tubulações, assegurando o correto funcionamento dos sistemas hidráulicos e sanitários.",
    },
    {
    id: 12316,
    nome: "Pintor",
    unid: "m²",
    valor: 15,
    descriçao: "Especialista em pintura e acabamento, responsável por aplicar tinta em superfícies internas e externas, garantindo a estética e proteção das estruturas.",
    },
    {
    id: 72342,
    nome: "Pedreiro de Acabamento",
    unid: "diária",
    valor: 280,
    descriçao: "Trabalhador que executa os acabamentos finais em construções, como colocação de pisos, azulejos, revestimentos e aplicação de massa corrida.",
    },
    {
    id: 1318,
    nome: "Carpinteiro",
    unid: "hr",
    valor: 320,
    descriçao: "Profissional que trabalha com madeira, realizando a montagem e construção de estruturas, como telhados, portas, janelas e escadas.",
    },
    {
    id: 2429,
    nome: "Mestre de Obras",
    unid: "mês",
    valor: 3500,
    descriçao: "Encarregado pela coordenação e supervisão da equipe de trabalho na obra, garantindo o cumprimento de prazos e a qualidade dos serviços executados.",
    },
    {
    id: 12340,
    nome: "Técnico em Edificações",
    unid: "mês",
    valor: 2800,
    descriçao: "Profissional que atua em projetos e execução de obras, colaborando com engenheiros e arquitetos na elaboração e acompanhamento de empreendimentos.",
    },
    {
    id: 112311,
    nome: "Operador de Máquinas Pesadas",
    unid: "hr",
    valor: 350,
    descriçao: "Responsável pela operação segura e eficiente de equipamentos pesados, como tratores, escavadeiras e retroescavadeiras, utilizados em obras e terraplanagem.",
    },
    {
    id: 12123,
    nome: "Montador de Andaimes",
    unid: "hr",
    valor: 180,
    descriçao: "Profissional especializado na montagem e desmontagem de estruturas de andaimes, garantindo a segurança dos trabalhadores durante a execução da obra.",
    },
    {
    id: 13234,
    nome: "Especialista em Instalações Elétricas",
    unid: "m²",
    valor: 20,
    descriçao: "Técnico habilitado a realizar instalações elétricas prediais, industriais ou comerciais, assegurando o correto funcionamento e segurança do sistema elétrico.",
    },
    {
    id: 134534,
    nome: "Marmorista",
    unid: "m²",
    valor: 50,
    descriçao: "Profissional especializado em trabalhar com mármore e granito, executando cortes, polimentos e acabamentos para revestimento de pisos, bancadas e fachadas.",
    }
]

export default ListaDeMaoDeObra;